package com.brown.main;

import com.brown.main.database.Database;
import com.brown.main.database.FirebaseHelper;
import com.brown.main.database.MongoHelper;
import com.brown.main.models.Area;
import com.brown.main.routes.RouteWrapper;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import org.bson.types.ObjectId;
import spark.Spark;

import java.util.ArrayList;
import java.util.List;

public final class App {
  private static final int DEFAULT_PORT = 4567;

  public static void main(String[] args) {
    Database<MongoDatabase> db = new MongoHelper("notSkiQL");
    MongoCollection collect = db.getDb("notSkiQL").getCollection("areas");
    Document doc = new Document();
    doc.append("name", "Killington");
    doc.append("num_trails", 155);
    doc.append("vert_drop", 3050);
    doc.append("acreage", 1509);
    doc.append("num_lifts", 21);
    doc.append("temperature", 17.8);
    doc.append("snow_quality", 0.2);
    doc.append("difficulty", 0.93);
    doc.append("location", "05751");
    doc.append("price", 169);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Sugarloaf");
    doc.append("num_trails", 162);
    doc.append("vert_drop", 2820);
    doc.append("acreage", 1240);
    doc.append("num_lifts", 13);
    doc.append("temperature", 11.8);
    doc.append("snow_quality", 0.06);
    doc.append("difficulty", 0.92);
    doc.append("location", "04947");
    doc.append("price", 125);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Sugarbush");
    doc.append("num_trails", 111);
    doc.append("vert_drop", 2650);
    doc.append("acreage", 581);
    doc.append("num_lifts", 16);
    doc.append("temperature", 22.6);
    doc.append("snow_quality", 0.34);
    doc.append("difficulty", 0.87);
    doc.append("location", "05674");
    doc.append("price", 169);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Smugglers' Notch");
    doc.append("num_trails", 78);
    doc.append("vert_drop", 2610);
    doc.append("acreage", 1000);
    doc.append("num_lifts", 8);
    doc.append("temperature", 26.4);
    doc.append("snow_quality", 1.00);
    doc.append("difficulty", 0.8);
    doc.append("location", "05464");
    doc.append("price", 90);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Stowe");
    doc.append("num_trails", 116);
    doc.append("vert_drop", 2360);
    doc.append("acreage", 485);
    doc.append("num_lifts", 12);
    doc.append("temperature", 15.3);
    doc.append("snow_quality", 0.38);
    doc.append("difficulty", 0.90);
    doc.append("location", "05672");
    doc.append("price", 172);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Sunday River");
    doc.append("num_trails", 135);
    doc.append("vert_drop", 2340);
    doc.append("acreage", 870);
    doc.append("num_lifts", 15);
    doc.append("temperature", 7.9);
    doc.append("snow_quality", 0.04);
    doc.append("difficulty", 0.84);
    doc.append("location", "04261");
    doc.append("price", 139);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Cannon Mountain");
    doc.append("num_trails", 97);
    doc.append("vert_drop", 2180);
    doc.append("acreage", 285);
    doc.append("num_lifts", 11);
    doc.append("temperature", 21.1);
    doc.append("snow_quality", 0.47);
    doc.append("difficulty", 0.95);
    doc.append("location", "03580");
    doc.append("price", 99);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Jay Peak");
    doc.append("num_trails", 81);
    doc.append("vert_drop", 2153);
    doc.append("acreage", 385);
    doc.append("num_lifts", 9);
    doc.append("temperature", 20.5);
    doc.append("snow_quality", 0.98);
    doc.append("difficulty", 0.94);
    doc.append("location", "05859");
    doc.append("price", 96);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Wildcat Mountain");
    doc.append("num_trails", 48);
    doc.append("vert_drop", 2112);
    doc.append("acreage",  225);
    doc.append("num_lifts", 5);
    doc.append("temperature", 22.5);
    doc.append("snow_quality", 0.05);
    doc.append("difficulty", 0.89);
    doc.append("location", "03846");
    doc.append("price", 99);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Loon Mountain");
    doc.append("num_trails", 61);
    doc.append("vert_drop", 2109);
    doc.append("acreage", 370);
    doc.append("num_lifts", 12);
    doc.append("temperature", 36.1);
    doc.append("snow_quality", 0.66);
    doc.append("difficulty", 0.72);
    doc.append("location", "03251");
    doc.append("price", 108);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Okemo Mountain");
    doc.append("num_trails", 119);
    doc.append("vert_drop", 2100);
    doc.append("acreage", 632);
    doc.append("num_lifts", 19);
    doc.append("temperature", 34.5);
    doc.append("snow_quality", 0.16);
    doc.append("difficulty", 0.76);
    doc.append("location", "05149");
    doc.append("price", 134);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Waterville Valley");
    doc.append("num_trails", 62);
    doc.append("vert_drop", 2020);
    doc.append("acreage", 265);
    doc.append("num_lifts", 12);
    doc.append("temperature", 31.3);
    doc.append("snow_quality", 0.84);
    doc.append("difficulty", 0.68);
    doc.append("location", "03215");
    doc.append("price", 102);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Buurke Mountain");
    doc.append("num_trails", 50);
    doc.append("vert_drop", 2011);
    doc.append("acreage", 267);
    doc.append("num_lifts", 4);
    doc.append("temperature", 14.5);
    doc.append("snow_quality", 0.33);
    doc.append("difficulty", 0.64);
    doc.append("location", "05832");
    doc.append("price", 85);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Stratton Mountain");
    doc.append("num_trails", 99);
    doc.append("vert_drop", 2003);
    doc.append("acreage", 670);
    doc.append("num_lifts", 11);
    doc.append("temperature", 13.7);
    doc.append("snow_quality", 0.58);
    doc.append("difficulty", 0.78);
    doc.append("location", "05630");
    doc.append("price", 169);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Mad River Glen");
    doc.append("num_trails", 45);
    doc.append("vert_drop", 2000);
    doc.append("acreage", 120);
    doc.append("num_lifts", 4);
    doc.append("temperature", 23.7);
    doc.append("snow_quality", 0.48);
    doc.append("difficulty", 0.97);
    doc.append("location", "05673");
    doc.append("price", 97);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Saddleback");
    doc.append("num_trails", 66);
    doc.append("vert_drop", 2000);
    doc.append("acreage", 600);
    doc.append("num_lifts", 5);
    doc.append("temperature", 9.1);
    doc.append("snow_quality", 0.42);
    doc.append("difficulty", 0.86);
    doc.append("location", "04970");
    doc.append("price", 99);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Pico Mountain");
    doc.append("num_trails", 57);
    doc.append("vert_drop", 1967);
    doc.append("acreage", 468);
    doc.append("num_lifts", 7);
    doc.append("temperature", 31.6);
    doc.append("snow_quality", 0.51);
    doc.append("difficulty", 0.83);
    doc.append("location", "05751");
    doc.append("price", 114);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Attitash");
    doc.append("num_trails", 75);
    doc.append("vert_drop", 1750);
    doc.append("acreage", 310);
    doc.append("num_lifts", 13);
    doc.append("temperature", 13.1);
    doc.append("snow_quality", 0.6);
    doc.append("difficulty", 0.66);
    doc.append("location", "03812");
    doc.append("price", 104);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Bolton Valley");
    doc.append("num_trails", 71);
    doc.append("vert_drop", 1704);
    doc.append("acreage", 300);
    doc.append("num_lifts", 6);
    doc.append("temperature", 22.3);
    doc.append("snow_quality", 0.4);
    doc.append("difficulty", 0.57);
    doc.append("location", "05477");
    doc.append("price", 99);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Mount Snow");
    doc.append("num_trails", 86);
    doc.append("vert_drop", 1700);
    doc.append("acreage", 600);
    doc.append("num_lifts", 20);
    doc.append("temperature", 25.8);
    doc.append("snow_quality", 0.24);
    doc.append("difficulty", 0.81);
    doc.append("location", "05356");
    doc.append("price", 129);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Mount Sunapee");
    doc.append("num_trails", 65);
    doc.append("vert_drop", 1510);
    doc.append("acreage", 233);
    doc.append("num_lifts", 10);
    doc.append("temperature", 11.8);
    doc.append("snow_quality", 0.44);
    doc.append("difficulty", 0.62);
    doc.append("location", "03782");
    doc.append("price", 114);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Bretton Woods");
    doc.append("num_trails", 101);
    doc.append("vert_drop", 1500);
    doc.append("acreage", 464);
    doc.append("num_lifts", 9);
    doc.append("temperature", 15.8);
    doc.append("snow_quality", 0.59);
    doc.append("difficulty", 0.81);
    doc.append("location", "03575");
    doc.append("price", 119);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Magic Mountain");
    doc.append("num_trails", 40);
    doc.append("vert_drop", 1500);
    doc.append("acreage", 195);
    doc.append("num_lifts", 4);
    doc.append("temperature", 16.8);
    doc.append("snow_quality", 0.67);
    doc.append("difficulty", 0.98);
    doc.append("location", "05148");
    doc.append("price", 74);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Tenney Mountain");
    doc.append("num_trails", 48);
    doc.append("vert_drop", 1440);
    doc.append("acreage", 110);
    doc.append("num_lifts", 5);
    doc.append("temperature", 22.7);
    doc.append("snow_quality", 0.81);
    doc.append("difficulty", 0.62);
    doc.append("location", "03264");
    doc.append("price", 59);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Gunstock Mountain");
    doc.append("num_trails", 50);
    doc.append("vert_drop", 1400);
    doc.append("acreage", 227);
    doc.append("num_lifts", 6);
    doc.append("temperature", 7.8);
    doc.append("snow_quality", 0.75);
    doc.append("difficulty", 0.67);
    doc.append("location", "03247");
    doc.append("price", 96);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Black Mountain (ME)");
    doc.append("num_trails", 35);
    doc.append("vert_drop", 1380);
    doc.append("acreage", 300);
    doc.append("num_lifts", 2);
    doc.append("temperature", 16.9);
    doc.append("snow_quality", 0.13);
    doc.append("difficulty", 0.61);
    doc.append("location", "04276");
    doc.append("price", 55);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Bromley");
    doc.append("num_trails", 45);
    doc.append("vert_drop", 1334);
    doc.append("acreage", 178);
    doc.append("num_lifts", 10);
    doc.append("temperature", 17.3);
    doc.append("snow_quality", 0.43);
    doc.append("difficulty", 0.66);
    doc.append("location", "05152");
    doc.append("price", 89);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Shawnee Peak");
    doc.append("num_trails", 40);
    doc.append("vert_drop", 1300);
    doc.append("acreage", 249);
    doc.append("num_lifts", 5);
    doc.append("temperature", 28.3);
    doc.append("snow_quality", 0.31);
    doc.append("difficulty", 0.63);
    doc.append("location", "04009");
    doc.append("price", 83);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Ragged Mountain");
    doc.append("num_trails", 47);
    doc.append("vert_drop", 1250);
    doc.append("acreage", 220);
    doc.append("num_lifts", 5);
    doc.append("temperature", 31.8);
    doc.append("snow_quality", 0.32);
    doc.append("difficulty", 0.65);
    doc.append("location", "03230");
    doc.append("price", 99);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Cranmore Mountain");
    doc.append("num_trails", 54);
    doc.append("vert_drop", 1200);
    doc.append("acreage", 200);
    doc.append("num_lifts", 10);
    doc.append("temperature", 21.7);
    doc.append("snow_quality", 0.62);
    doc.append("difficulty", 0.7);
    doc.append("location", "03860");
    doc.append("price", 99);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Berkshire East");
    doc.append("num_trails", 45);
    doc.append("vert_drop", 1180);
    doc.append("acreage", 180);
    doc.append("num_lifts", 6);
    doc.append("temperature", 26.8);
    doc.append("snow_quality", 0.78);
    doc.append("difficulty", 0.78);
    doc.append("location", "01339");
    doc.append("price", 92);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Mount Abram");
    doc.append("num_trails", 44);
    doc.append("vert_drop", 1150);
    doc.append("acreage", 450);
    doc.append("num_lifts", 5);
    doc.append("temperature", 42.8);
    doc.append("snow_quality", 0.77);
    doc.append("difficulty", 0.52);
    doc.append("location", "04255");
    doc.append("price", 55);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Jiminy Peak");
    doc.append("num_trails", 45);
    doc.append("vert_drop", 1140);
    doc.append("acreage", 170);
    doc.append("num_lifts", 8);
    doc.append("temperature", 26.7);
    doc.append("snow_quality", 0.21);
    doc.append("difficulty", 0.57);
    doc.append("location", "01237");
    doc.append("price", 91);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Ski Butternut");
    doc.append("num_trails", 22);
    doc.append("vert_drop", 1000);
    doc.append("acreage", 110);
    doc.append("num_lifts", 10);
    doc.append("temperature", 21.4);
    doc.append("snow_quality", 0.36);
    doc.append("difficulty", 0.43);
    doc.append("location", "01230");
    doc.append("price", 75);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Black Mountain (NH)");
    doc.append("num_trails", 40);
    doc.append("vert_drop", 1110);
    doc.append("acreage", 143);
    doc.append("num_lifts", 4);
    doc.append("temperature", 27.5);
    doc.append("snow_quality", 0.64);
    doc.append("difficulty", 0.5);
    doc.append("location", "03846");
    doc.append("price", 62);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Middlebury College Ski Bowl");
    doc.append("num_trails", 17);
    doc.append("vert_drop", 1040);
    doc.append("acreage", 1110);
    doc.append("num_lifts", 3);
    doc.append("temperature", 14.1);
    doc.append("snow_quality", 0.01);
    doc.append("difficulty", 0.64);
    doc.append("location", "05748");
    doc.append("price", 55);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);

    doc=new Document();
    doc.append("name", "Crotched Mountain");
    doc.append("num_trails", 23);
    doc.append("vert_drop", 1016);
    doc.append("acreage", 100);
    doc.append("num_lifts", 5);
    doc.append("temperature", 24.2);
    doc.append("snow_quality", 0.48);
    doc.append("difficulty", 0.43);
    doc.append("location", "03442");
    doc.append("price", 84);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Wachusett Mountain");
    doc.append("num_trails", 22);
    doc.append("vert_drop", 1000);
    doc.append("acreage", 110);
    doc.append("num_lifts", 7);
    doc.append("temperature", 24.2);
    doc.append("snow_quality", 0.41);
    doc.append("difficulty", 0.46);
    doc.append("location", "01541");
    doc.append("price", 72);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Catamount");
    doc.append("num_trails", 43);
    doc.append("vert_drop", 1000);
    doc.append("acreage", 100);
    doc.append("num_lifts", 4);
    doc.append("temperature", 23.0);
    doc.append("snow_quality", 0.93);
    doc.append("difficulty", 0.54);
    doc.append("location", "01258");
    doc.append("price", 79);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Bigrock");
    doc.append("num_trails", 28);
    doc.append("vert_drop", 980);
    doc.append("acreage", 60);
    doc.append("num_lifts", 5);
    doc.append("temperature", 37.2);
    doc.append("snow_quality", 0.46);
    doc.append("difficulty", 0.43);
    doc.append("location", "04758");
    doc.append("price", 45);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Dartmouth Skiway");
    doc.append("num_trails", 31);
    doc.append("vert_drop", 968);
    doc.append("acreage", 107);
    doc.append("num_lifts", 5);
    doc.append("temperature", 23.6);
    doc.append("snow_quality", 0.55);
    doc.append("difficulty", 0.37);
    doc.append("location", "03768");
    doc.append("price", 53);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Camden Ski Bowl");
    doc.append("num_trails", 11);
    doc.append("vert_drop", 943);
    doc.append("acreage", 60);
    doc.append("num_lifts", 5);
    doc.append("temperature", 33.5);
    doc.append("snow_quality", 0.18);
    doc.append("difficulty", 0.45);
    doc.append("location", "04843");
    doc.append("price", 45);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Bousquet");
    doc.append("num_trails", 23);
    doc.append("vert_drop", 750);
    doc.append("acreage", 200);
    doc.append("num_lifts", 5);
    doc.append("temperature", 13.6);
    doc.append("snow_quality", 0.11);
    doc.append("difficulty", 0.53);
    doc.append("location", "01201");
    doc.append("price", 72);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Pats Peak");
    doc.append("num_trails", 23);
    doc.append("vert_drop", 710);
    doc.append("acreage", 90);
    doc.append("num_lifts", 10);
    doc.append("temperature", 12.6);
    doc.append("snow_quality", 0.09);
    doc.append("difficulty", 0.27);
    doc.append("location", "03242");
    doc.append("price", 89);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Whaleback");
    doc.append("num_trails", 30);
    doc.append("vert_drop", 700);
    doc.append("acreage", 85);
    doc.append("num_lifts", 4);
    doc.append("temperature", 28.1);
    doc.append("snow_quality", 0.27);
    doc.append("difficulty", 0.44);
    doc.append("location", "03748");
    doc.append("price", 50);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Mohawk Mountain");
    doc.append("num_trails", 25);
    doc.append("vert_drop", 650);
    doc.append("acreage", 107);
    doc.append("num_lifts", 7);
    doc.append("temperature", 21.1);
    doc.append("snow_quality", 0.39);
    doc.append("difficulty", 0.43);
    doc.append("location", "06753");
    doc.append("price", 70);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Suicide Six");
    doc.append("num_trails", 23);
    doc.append("vert_drop", 650);
    doc.append("acreage", 100);
    doc.append("num_lifts", 3);
    doc.append("temperature", 14.1);
    doc.append("snow_quality", 0.);
    doc.append("difficulty", 0.53);
    doc.append("location", "05067");
    doc.append("price", 89);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Ski Sundown");
    doc.append("num_trails", 15);
    doc.append("vert_drop", 625);
    doc.append("acreage", 65);
    doc.append("num_lifts", 5);
    doc.append("temperature", 10.3);
    doc.append("snow_quality", 0.28);
    doc.append("difficulty", 0.35);
    doc.append("location", "06057");
    doc.append("price", 64);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Powder Ridge");
    doc.append("num_trails", 20);
    doc.append("vert_drop", 550);
    doc.append("acreage", 80);
    doc.append("num_lifts", 3);
    doc.append("temperature", 1.88);
    doc.append("snow_quality", 0.1);
    doc.append("difficulty", 0.18);
    doc.append("location", "06455");
    doc.append("price", 49);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Cochran's Ski Area");
    doc.append("num_trails", 6);
    doc.append("vert_drop", 500);
    doc.append("acreage", 30);
    doc.append("num_lifts", 5);
    doc.append("temperature", 1.72);
    doc.append("snow_quality", 0.74);
    doc.append("difficulty", 0.13);
    doc.append("location", "05477");
    doc.append("price", 19);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Arrowhead");
    doc.append("num_trails", 9);
    doc.append("vert_drop", 500);
    doc.append("acreage", 50);
    doc.append("num_lifts", 2);
    doc.append("temperature", 20.6);
    doc.append("snow_quality", 0.08);
    doc.append("difficulty", 0.12);
    doc.append("location", "03743");
    doc.append("price", 9);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Mount Southington");
    doc.append("num_trails", 14);
    doc.append("vert_drop", 425);
    doc.append("acreage", 51);
    doc.append("num_lifts", 7);
    doc.append("temperature", 27.5);
    doc.append("snow_quality", 0.86);
    doc.append("difficulty", 0.04);
    doc.append("location", "06479");
    doc.append("price", 64);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Otis Ridge");
    doc.append("num_trails", 11);
    doc.append("vert_drop", 400);
    doc.append("acreage", 60);
    doc.append("num_lifts", 5);
    doc.append("temperature", 17.4);
    doc.append("snow_quality", 0.68);
    doc.append("difficulty", 0.15);
    doc.append("location", "01253");
    doc.append("price", 40);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Hermon Mountain");
    doc.append("num_trails", 18);
    doc.append("vert_drop", 350);
    doc.append("acreage", 75);
    doc.append("num_lifts", 3);
    doc.append("temperature", 12.4);
    doc.append("snow_quality", 0.97);
    doc.append("difficulty", 0.22);
    doc.append("location", "04401");
    doc.append("price", 55);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Titcomb Mountain");
    doc.append("num_trails", 16);
    doc.append("vert_drop", 350);
    doc.append("acreage", 45);
    doc.append("num_lifts", 2);
    doc.append("temperature", 27.2);
    doc.append("snow_quality", 0.83);
    doc.append("difficulty", 0.16);
    doc.append("location", "04938");
    doc.append("price", 30);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "King Pine");
    doc.append("num_trails", 17);
    doc.append("vert_drop", 3050);
    doc.append("acreage", 45);
    doc.append("num_lifts", 6);
    doc.append("temperature", 16.7);
    doc.append("snow_quality", 0.35);
    doc.append("difficulty", 0.07);
    doc.append("location", "03849");
    doc.append("price", 65);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Blue Hills");
    doc.append("num_trails", 12);
    doc.append("vert_drop", 309);
    doc.append("acreage", 60);
    doc.append("num_lifts", 4);
    doc.append("temperature", 21.);
    doc.append("snow_quality", 0.71);
    doc.append("difficulty", 0.08);
    doc.append("location", "02021");
    doc.append("price", 58);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Ski Bradford");
    doc.append("num_trails", 15);
    doc.append("vert_drop", 248);
    doc.append("acreage", 48);
    doc.append("num_lifts", 10);
    doc.append("temperature", 18.6);
    doc.append("snow_quality", 0.15);
    doc.append("difficulty", 0.17);
    doc.append("location", "01830");
    doc.append("price", 65);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Yawgoo Valley");
    doc.append("num_trails", 12);
    doc.append("vert_drop", 245);
    doc.append("acreage", 36);
    doc.append("num_lifts", 4);
    doc.append("temperature", 23.7);
    doc.append("snow_quality", 0.7);
    doc.append("difficulty", 0.01);
    doc.append("location", "02822");
    doc.append("price", 55);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Lost Valley");
    doc.append("num_trails", 17);
    doc.append("vert_drop", 240);
    doc.append("acreage", 45);
    doc.append("num_lifts", 2);
    doc.append("temperature", 18.8);
    doc.append("snow_quality", 0.91);
    doc.append("difficulty", 0.11);
    doc.append("location", "04210");
    doc.append("price", 60);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Nashoba Valley");
    doc.append("num_trails", 17);
    doc.append("vert_drop", 240);
    doc.append("acreage", 59);
    doc.append("num_lifts", 9);
    doc.append("temperature", 26.6);
    doc.append("snow_quality", 0.69);
    doc.append("difficulty", 0.02);
    doc.append("location", "01886");
    doc.append("price", 65);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Ski Ward");
    doc.append("num_trails", 9);
    doc.append("vert_drop", 220);
    doc.append("acreage", 45);
    doc.append("num_lifts", 6);
    doc.append("temperature", 16.8);
    doc.append("snow_quality", 0.99);
    doc.append("difficulty", 0.);
    doc.append("location", "01545");
    doc.append("price", 60);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "Abenaki Ski Area");
    doc.append("num_trails", 7);
    doc.append("vert_drop", 200);
    doc.append("acreage", 18);
    doc.append("num_lifts", 2);
    doc.append("temperature", 34.2);
    doc.append("snow_quality", 0.25);
    doc.append("difficulty", 0.1);
    doc.append("location", "03894");
    doc.append("price", 16);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    doc=new Document();
    doc.append("name", "McIntyre");
    doc.append("num_trails", 9);
    doc.append("vert_drop", 147);
    doc.append("acreage", 100);
    doc.append("num_lifts", 2);
    doc.append("temperature", 18.7);
    doc.append("snow_quality", 0.26);
    doc.append("difficulty", 0.03);
    doc.append("location", "03101");
    doc.append("price", 48);
    doc.append("comments", new ArrayList<ObjectId>());
    collect.insertOne(doc);
    new App(args).run();
  }

  private String[] args;

  private App(String[] args) {
    this.args = args;
  }

  private void run() {
    System.out.println("Starting server...");
    runSparkServer(DEFAULT_PORT);
  }

  private static void runSparkServer(int port) {
    Spark.port(port);

    Spark.options("/*", (request, response) -> {
      String accessControlRequestHeaders = request.headers("Access-Control-Request-Headers");
      if (accessControlRequestHeaders != null) {
        response.header("Access-Control-Allow-Headers", accessControlRequestHeaders);
      }

      String accessControlRequestMethod = request.headers("Access-Control-Request-Method");

      if (accessControlRequestMethod != null) {
        response.header("Access-Control-Allow-Methods", accessControlRequestMethod);
      }

      return "OK";
    });

    Spark.before((request, response) -> response.header("Access-Control-Allow-Origin", "*"));

    // set up firebase service
    FirebaseHelper.initFirebase();
    // create new db
    Database<MongoDatabase> db = new MongoHelper("notSkiQL");
    RouteWrapper rw = new RouteWrapper(db.getDb("notSkiQL"));
    rw.initRoutes();

    Spark.init();
  }
}
